name: team_alert
description: Team alert system
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.0.0
  firebase_messaging: ^14.0.0
  http: ^0.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
